services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker_data/crawler:/data

  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker_data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
