FROM python:3.13-slim

ENV DEBIAN_FRONTEND=noninteractive \
  TZ=Europe/Zagreb

RUN apt-get update && \
  apt-get install -y --no-install-recommends tzdata && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml .
RUN pip install --upgrade pip setuptools wheel && \
  pip install --no-cache-dir ".[service]"

COPY service /app/service

EXPOSE 8000

CMD ["python", "-m", "service.main"]